name: Backend Test

on: [push]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Composer
      uses: php-actions/composer@v5

    - name: Unit Tests
      uses: php-actions/phpunit@v3
