name: Backend Test

on: [push]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Dir
      run: pwd

    - name: Setup PHP
      uses: shivammathur/setup-php@v2

    - name: Install dependencies
      run: composer install

    - name: Unit Tests
      uses: php-actions/phpunit@v3
